### PR TITLE
#167727453:user validation on signup

### PR DESCRIPTION
**Pull request by danndav**
### What does this PR do?
Creates validation middlewares for signup 

### Description of Task to be completed?
Write signup validation middlewares
Add custom sanitation helper functions
Create a middleware to check for validation errors
How should this be manually tested?
Pull this branch to your local
Run npm test in your console
Open Postman and test the endpoint at /api/v1/auth/signup with missing or invalid input
Any background context you want to provide?
N/A

### What are the relevant pivotal tracker stories?
#167727453

###Screenshots (if appropriate)

### CODE REVIEW

**Review by parkerthegeniuschild — COMMENTED** [review]
I'll be able to review this within an hour or two. Meanwhile, get ready to `squash your commits`.

**Review by chiomadans1759 — CHANGES_REQUESTED** [review]
@danndav Kindly squash your commits into one

**Comment by chiomadans1759** [comment]
Kindly use the `/api/v1/auth/signup` router in the `router/api/auth.router.js` file already in use. Just pass your validation middleware there. Delete the `router/api/user.js`,and the router/api/index.js file because they are no longer in use. Kindly confirm from other teammates just to be clear.


Screen Shot 2019-09-03 at 11 02 21 PM

**Comment by chiomadans1759** [comment]
Also Make validations for when a user sends an empty request body and when a user trying to signup already exists. Check to see that the new user email does not exist in the database and return a relevant error message if this is violated.

Best Regards!!

**Comment by chiomadans1759** [comment]
Kindly write more tests cases to cover the new validations pointed out above, and also for the `user.validation` middleware you created. Thanks

**Comment by danndav** [comment]
> Also Make validations for when a user sends an empty request body and when a user trying to signup already exists. Check to see that the new user email does not exist in the database and return a relevant error message if this is violated.
> 
> Best Regards!!

thanks for the feedback, i have been able to implement the feedback

**Pull request closed without merging**
