### PR TITLE
#168250881 Get All Ratings

### PR DESCRIPTION
**Pull request by parkerthegeniuschild**
#### What does this PR do?
Allows users to view ratings of a facility even without being logged in.

#### Description of Task to be completed?
image

#### How should this be manually tested?
Use an API Tool and hit the endpoint: `/GET /api/v1/rating/facility/:id`

#### Any background context you want to provide?
Route is not authenticated, users do not need to login.

#### What are the relevant pivotal tracker stories?
[#168250881](https://www.pivotaltracker.com/story/show/168250881)

### CODE REVIEW

**Review by chiomadans1759 — CHANGES_REQUESTED** [review]
Good job! @parkerthegeniuschild However, Kindly go through the specification for this task again!!. For each facility, you are required to return the `count` for each rating level. For instance  
```
"rating1": 2,
"rating2": 0,
"rating3": 0,
"rating4": 1,
"rating5": 3
```
Kindly Implement this changed. Cheers!

**Comment by chiomadans1759** [comment]
Also ensure that you document your endpoint using swagger as this is a requirement for this task. Thanks

**Comment by O-Osahon** [comment]
This endpoint should be authenticated; every endpoint should be. I understand why you made it this way, however, remember it is a closed platform. Non-employees of the company should not be allowed to access any page, save the authentication pages.

**Comment by parkerthegeniuschild** [comment]
> Good job! @parkerthegeniuschild However, Kindly go through the specification for this task again!!. For each facility, you are required to return the `count` for each rating level. For instance
> 
> ```
> "rating1": 2,
> "rating2": 0,
> "rating3": 0,
> "rating4": 1,
> "rating5": 3
> ```
> 
> Kindly Implement this changed. Cheers!

This does not say much. Can you run the code, take the response, and edit it, then paste it here as a sample response here based on spec?

**Comment by parkerthegeniuschild** [comment]
> This endpoint should be authenticated; every endpoint should be. I understand why you made it this way, however, remember it is a closed platform. Non-employees of the company should not be allowed to access any page, save the authentication pages.

The story said the route should be accessible even when `a user is not logged in`

**Comment by chiomadans1759** [comment]
> > Good job! @parkerthegeniuschild However, Kindly go through the specification for this task again!!. For each facility, you are required to return the `count` for each rating level. For instance
> > ```
> > "rating1": 2,
> > "rating2": 0,
> > "rating3": 0,
> > "rating4": 1,
> > "rating5": 3
> > ```
> > 
> > 
> > Kindly Implement this changed. Cheers!
> 
> This does not say much. Can you run the code, take the response, and edit it, then paste it here as a sample response here based on spec?

This is the response from your endpoint @parkerthegeniuschild 
Screen Shot 2019-09-09 at 3 34 01 PM

The story says  `the metrics of all ratings on each accommodation facility`. So you are returning just the metrics count for each rating level and not the entire rating respoint. We only need the counts on the frontend.
Screen Shot 2019-09-09 at 3 36 51 PM

**Pull request merged**
