### PR TITLE
#167727484 Users Can Provide Ratings & Optional Feedback

### PR DESCRIPTION
**Pull request by parkerthegeniuschild**
#### What does this PR do?
This allows users to provide feedback for a facility

#### How should this be manually tested?
`/POST /api/v1/feedback/facility/:id`

#### Any background context you want to provide?

- The route is protected; so you need a `Bearer <token>`
- Request body should contain `feedback: "this is a sample feedback blah blah blah"`

#### What are the relevant pivotal tracker stories?
[#167727484](https://www.pivotaltracker.com/story/show/167727484)

### CODE REVIEW

**Comment by chiomadans1759** [comment]
@parkerthegeniuschild I tried to test this endpoint but I didn't see anything concerning rating like the name of your PR signifies. Is this a mistake? If yes, kindly rename the PR to suit the functionality

Screen Shot 2019-09-09 at 3 10 35 PM

**Comment by chiomadans1759** [comment]
We also said that only users who are `checked-in`  can rate or provide feedback for a facility. Can you put this into consideration please. Cheers

**Comment by parkerthegeniuschild** [comment]
> We also said that only users who are `checked-in` can rate or provide feedback for a facility. Can you put this into consideration please. Cheers

This comment is `highly unnecessary`. Please read the tag.

**Comment by parkerthegeniuschild** [comment]
> @parkerthegeniuschild I tried to test this endpoint but I didn't see anything concerning rating like the name of your PR signifies. Is this a mistake? If yes, kindly rename the PR to suit the functionality
> 
> Screen Shot 2019-09-09 at 3 10 35 PM

[x] Tag says `WORK-IN-PROGRESS` not `READY FOR REVIEW` 5 HOURS AGO !!!!
---

**Pull request closed without merging**
