### PR TITLE
#167727443 Setup travisci with readme badge

### PR DESCRIPTION
**Pull request by jiokeokwuosa**
What does this PR do?
Integrate TravisCI with badge attached to readme

Description of Task to be completed?
-activate TravisCI for northstar-backend repository
-add a .travis.yml file at the project's root folder
-integrate TravisCI badge in readme file

Any background context you want to provide?
TravisCI is a hosted continous integration service used to build and test software projects hosted at Github

What are the relevant pivotal tracker stories?
#167727443

Screenshots (if appropriate)
Screenshot (463)

### CODE REVIEW

**Review by Qausim — COMMENTED** [review]
@jiokeokwuosa, is it required to append a "v" in the node version inside `.travis.yml`? And Travis itself seems to be falling the branch since there isn't a valid "test" script to run yet. You may have to wait for #11 to get merged first.

**Comment by jiokeokwuosa** [comment]
There is a "V" there @Qausim

**Comment by Qausim** [comment]
> There is a "V" there @Qausim

Yeah it is, @jiokeokwuosa. I was just asking if it should be there.

**Review by parkerthegeniuschild — CHANGES_REQUESTED** [review]
Great job setting up Travis. However, you will need to implement more tasks for travis e.g spinning up a `pg service` and caching your `node_modules` folder to make builds faster. Since there are not tests for now; you want to change the test script line to `exit 0` instead of `exit 1`; so it's will do a `false pass`.
You can leverage this screenshot for help.

image

**Review by parkerthegeniuschild — APPROVED** [review]
Good job. Travis is now passing.
 Could you help copy the Travis ReadMe badge?
Thank you.

**Pull request merged**
