### PR TITLE
#168250754 Fetch Single Travel Request

### PR DESCRIPTION
**Pull request by Qausim**
#### What does this PR do?
Provides the implementation to fetch a single travel request by its ID

#### Description of Task to be completed?
- Have endpoint GET `/api/v1/requests/:request_id` working
- Document endpoint using Swagger

#### How should this be manually tested?
Clone this repo, cd into it and 
- Run `npm test`
- Or run `npm run start:dev`, then using an API test tool like Postman send GET requests to
  `/api/v1/requests/:request_id` on localhost
_key_: Port value: 3000
_key_: requires bearer token authentication

#### Any background context you want to provide?
A user should be able to view one of his/her requests, a manager should be able to view a single request of a user under his management, and a superadmin should be able to view any request

#### What are the relevant pivotal tracker stories?
[#168250754](https://www.pivotaltracker.com/story/show/168250754)

#### Screenshots (if appropriate)
None

#### Questions:
None

### CODE REVIEW

**Review by parkerthegeniuschild — CHANGES_REQUESTED** [review]
[x] Clean up `your reponse. user_id & booking_id are duplicated`. You should return the `JOINED` models as `aliases` to ensure they are `snake(lower)_cased` e.g `User as user && Booking as booking`
---
image
---
[x] Just say {Object} req
---
image
---

**Comment by Qausim** [comment]
> ## [x] Clean up `your reponse. user_id & booking_id are duplicated`. You should return the `JOINED` models as `aliases` to ensure they are `snake(lower)_cased` e.g `User as user && Booking as booking`
> ## image
> ## [x] Just say {Object} req
> ## image

The duplicated ids serve in testing that the returned booking and user are indeed those referenced by the resulting travel requests. I believe the duplication is trivial when compared to ensuring the data turns out as expected

Also, to modify `"User"` and `"Booking"` I may have to modify the model associations. I don't know how that will affect existing features and it seem too trivial compared to what it might break

**Review by chiomadans1759 — DISMISSED** [review]
Nice Job! @Qausim However, a user should only be able to get one of his requests while a manager/super_admin can get any single request. Kindly go through the story over again https://www.pivotaltracker.com/story/show/168250754. Cheers


Screen Shot 2019-09-08 at 2 11 18 PM

**Comment by chiomadans1759** [comment]
Also make adjustment to your endpoint documentation. Include a sample response object. Cheers

**Review by chiomadans1759 — APPROVED** [review]

**Comment by parkerthegeniuschild** [comment]
> > ## [x] Clean up `your reponse. user_id & booking_id are duplicated`. You should return the `JOINED` models as `aliases` to ensure they are `snake(lower)_cased` e.g `User as user && Booking as booking`
> > ## image
> > ## [x] Just say {Object} req
> > ## image
> 
> The duplicated ids serve in testing that the returned booking and user are indeed those referenced by the resulting travel requests. I believe the duplication is trivial when compared to ensuring the data turns out as expected
> 
> Also, to modify `"User"` and `"Booking"` I may have to modify the model associations. I don't know how that will affect existing features and it seem too trivial compared to what it might break

> Great concepts. Come to think of it, that's we have a branch locally. You can modify it there and sees if it breaks anything. If it doesn't, you make the PR and somebody else will test and see if it still breaks and if it doesn't; all is well that ends well. Besides, you will ONLY be returning the referenced tables as aliases; right from your logic.  **You should try it out first, then if you don't like the LOOK of it, you can revert.** And when it comes to building world-class software, nothing is too `trivial` to be left to `chance`; perhaps. Thank you for understanding.

I do understand your view. However, projects are normally in continuum, I may not be the one working on a branch that breaks it and the person may not know what modifications I made. Including the id field in `Booking` `User` is not buggy (hence why I said trivial) when compared to ensuring the referenced models are indeed the one on the request.
Also, about the aliases, I tried it already and the SQL is not taking `as: booking` and `as: user` but throws errors because it expects `Booking` and `User`

**Pull request merged**
