### PR TITLE
#168250889 Get All Feedback

### PR DESCRIPTION
**Pull request by parkerthegeniuschild**
#### What does this PR do?
Allows a super admin and/or travel admin to get all feedback for a facility.

#### Description of Task to be completed?
image

#### How should this be manually tested?
Checkout this PR and use any API Testing tool to hit the endpoint below:
`/GET /api/v1/feedback/facility/:id`

#### Any background context you want to provide?
Route needs authentication via `Bearer <token>` and is only accessible by a `super_admin or travel_admin.`

#### What are the relevant pivotal tracker stories?
[#168250889](https://www.pivotaltracker.com/story/show/168250889)

### CODE REVIEW

**Review by chiomadans1759 — CHANGES_REQUESTED** [review]
Good Job! @parkerthegeniuschild Your endpoint allows only super_admin to get feedback at this time. The expected functionality is that super_admin should be able to get all feedback and travel_admin should be able to get feedback on all their facilities. Kindly implement this!

Screen Shot 2019-09-08 at 4 09 25 PM

Kindly go through the requirement of the story again. Thanks
Screen Shot 2019-09-08 at 4 15 41 PM

**Review by O-Osahon — COMMENTED** [review]
I thought the `GET ALL feedback` and `ratings` feature ought to be on one endpoint and story. At least, that was what the Product Owner said. Did you confirm the separation from him?

**Comment by parkerthegeniuschild** [comment]
> Good Job! @parkerthegeniuschild Your endpoint allows only super_admin to get feedback at this time. The expected functionality is that super_admin should be able to get all feedback and travel_admin should be able to get feedback on all their facilities. Kindly implement this!
> 
> Screen Shot 2019-09-08 at 4 09 25 PM
> 
> Kindly go through the requirement of the story again. Thanks
> Screen Shot 2019-09-08 at 4 15 41 PM

Copied !!!

**Comment by parkerthegeniuschild** [comment]
> I thought the `GET ALL feedback` and `ratings` feature ought to be on one endpoint and story. At least, that was what the Product Owner said. Did you confirm the separation from him?

For the sake of sanity, let's leave them at 2 endpoints, because according to the story, while both of them are get requests, one is only accessible by admins and the other is open to the general public

**Pull request merged**
