### PR TITLE
#168191152 fix test script

### PR DESCRIPTION
**Pull request by O-Osahon**
### What does this PR do?
- It fixes the test script and ensures tests run on Windows, Linux and Mac Operating Systems

### How can this be manually tested?
-  Clone or download this repository
-  On your terminal, `cd` into the application's directory and run: `git branch -r` to get all the branches from the origin
- Run `git checkout -b bg-test-168191152 origin/bg-test-168191152` to have a copy of this branch locally
-  Set the following environment variables in your `.env` file:
```
DB_PASSWORD_DEVELOPMENT // db password
DB_NAME_DEVELOPMENT // db name
DB_HOST_DEVELOPMENT // host: If  not set, this defaults to 'localhost'
DB_DIALECT=postgres // If not set, this defaults to 'postgres'
```

- If you have not, install [Postgresql](https://www.postgresql.org/download)
- Run `npm run test`
- Your test script should run

#### Any background context you want to provide?
- A couple of tests will fail and ten will pass. You don't have to worry about this. It has nothing to do with this Pull Request.

### What are the relevant Pivotal Tacker stories?
[#168191152 ](https://www.pivotaltracker.com/story/show/168191152)

### CODE REVIEW

**Review by oleesir — APPROVED** [review]
my test is passed...

**Review by parkerthegeniuschild — CHANGES_REQUESTED** [review]
1. Could you update your PR story to inform your users that while you can set the `DB_DIALECT=postgres`; if you forget to do so; it defaults to `postgres` because there is a default fallback option.

2. I think it is not necessary to do `./node_modules/.bin/sequelize` it locks you to the current working directory. While this may suffice for smaller projects, you might run into binary issues when you intend to scale your app redundantly.

3. Add a ```--timeout``` of say 20 s or so to the `nyc` task. Although that would mask the underlying problems. There is a problem with the `signup test` taking too long to complete. I suggest you reach out to who wrote it and see if they can refactor and push along with their next commit, taking very good care not to break the application; whilst calling our attention to it.

Hurray . . . good job !!!!

**Comment by O-Osahon** [comment]
> 1. Could you update your PR story to inform your users that while you can set the `DB_DIALECT=postgres`; if you forget to do so; it defaults to `postgres` because there is a default fallback option.
> 2. I think it is not necessary to do `./node_modules/.bin/sequelize` it locks you to the current working directory. While this may suffice for smaller projects, you might run into binary issues when you intend to scale your app redundantly.
> 3. Add a `--timeout` of say 20 s or so to the `nyc` task. Although that would mask the underlying problems. There is a problem with the `signup test` taking too long to complete. I suggest you reach out to who wrote it and see if they can refactor and push along with their next commit, taking very good care not to break the application; whilst calling our attention to it.
> 
> Hurray . . . good job !!!!

1. I'll fix the PR now.

2. I'm using that in place of the globally installed `sequelize-cli`. I did it to ensure that any machine the app needs to run on does not need to install sequelize-cli globally.

3. No problem. I'll do that. However, there will be a slight delay because my pc is down. I'll push the change as soon as possible

**Comment by O-Osahon** [comment]
@parkerthegeniuschild I was wrong. The sequelize main package and not the `sequelize-cli` is used for migration. I have removed the `./node_modules/...`

**Review by parkerthegeniuschild — APPROVED** [review]

**Pull request merged**
